### ISSUE TITLE
rename mobs in datapack

### ISSUE THREAD

**Issue by Doquancht** [HanalinchEve/AdvancedMobs#1]
How can I rename all mobs in the datapack?

**Comment by HanalinchEve** [comment]
All mobs in the datapack are unnamed by default, and only those summoned with spawn egg are named based on the name of the spawn egg item, you can use anvil to rename the spawn egg.  
If you are familiar with minecraft commands and nbt, you can add a "  ,CustomimName: '[{"text": "NAME"}]'    " at the end of the first two lines in "AdvancedMobs\data\advancedmobs\function\ss\\"mob name"\0.mcfunction".  
You can also ask me to help you modify it :)

**Comment by Doquancht** [comment]
Thanks
